### ISSUE TITLE
Unable to run migrations in a fresh django project

### ISSUE THREAD

**Issue by h4roldov** [aaronkazah/django-libsql#1]
I started a new project and add my turso db to the config but i am getting the following error when running initial migrations:

Unable` to create the django_migrations table (HRANA_WEBSOCKET_ERROR: WebSocket was closed)

**Comment by aaronkazah** [comment]
@h4roldov can you share the steps you you took to get that error?

**Comment by h4roldov** [comment]
It was an issue with the multi-db schema option in turso, it worked with a "normal" database. Thanks
